//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeTrain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeTrain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year {0} Month {1} Day {2} ({3}) {4,2:d}:{5,1:d}0.
        /// </summary>
        internal static string CLOCK_FORMAT {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        internal static string CONTROLLER_EXIT_BUTTON {
            get {
                return ResourceManager.GetString("CONTROLLER_EXIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string CONTROLLER_PLACE_BUTTON {
            get {
                return ResourceManager.GetString("CONTROLLER_PLACE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click two points on the map to place tracks.
        /// </summary>
        internal static string CONTROLLER_RAIL_INITIAL_MESSAGE {
            get {
                return ResourceManager.GetString("CONTROLLER_RAIL_INITIAL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are obstacles in the way.
        /// </summary>
        internal static string CONTROLLER_RAIL_OBSTACLES {
            get {
                return ResourceManager.GetString("CONTROLLER_RAIL_OBSTACLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select starting point.
        /// </summary>
        internal static string CONTROLLER_RAIL_START_POINT {
            get {
                return ResourceManager.GetString("CONTROLLER_RAIL_START_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAILROAD.
        /// </summary>
        internal static string CONTROLLER_RAIL_TITLE {
            get {
                return ResourceManager.GetString("CONTROLLER_RAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string CONTROLLER_REMOVE_BUTTON {
            get {
                return ResourceManager.GetString("CONTROLLER_REMOVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string FRIDAY {
            get {
                return ResourceManager.GetString("FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeTrain SDL.
        /// </summary>
        internal static string MAIN_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string MONDAY {
            get {
                return ResourceManager.GetString("MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string SATURDAY {
            get {
                return ResourceManager.GetString("SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the TAO SDL Framework\nPlease download it from http://www.taoframework.com/\n\nThis application will now close..
        /// </summary>
        internal static string SDL_NOT_FOUND {
            get {
                return ResourceManager.GetString("SDL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string SUNDAY {
            get {
                return ResourceManager.GetString("SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string THURSDAY {
            get {
                return ResourceManager.GetString("THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string TUESDAY {
            get {
                return ResourceManager.GetString("TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string WEDNESDAY {
            get {
                return ResourceManager.GetString("WEDNESDAY", resourceCulture);
            }
        }
    }
}
