//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeTrain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeTrain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year {0} Month {1} Day {2} ({3}) {4,2:d}:{5,1:d}0.
        /// </summary>
        internal static string CLOCK_FORMAT {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t build object!.
        /// </summary>
        internal static string CONSTRUCTION_CANNOT_BUILD {
            get {
                return ResourceManager.GetString("CONSTRUCTION_CANNOT_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t place this object!.
        /// </summary>
        internal static string CONSTRUCTION_CANNOT_PLACE {
            get {
                return ResourceManager.GetString("CONSTRUCTION_CANNOT_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove object!.
        /// </summary>
        internal static string CONSTRUCTION_CANNOT_REMOVE {
            get {
                return ResourceManager.GetString("CONSTRUCTION_CANNOT_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string CONTROLLER_BUILD_BUTTON {
            get {
                return ResourceManager.GetString("CONTROLLER_BUILD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost:.
        /// </summary>
        internal static string CONTROLLER_COST_LABEL {
            get {
                return ResourceManager.GetString("CONTROLLER_COST_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        internal static string CONTROLLER_EXIT_BUTTON {
            get {
                return ResourceManager.GetString("CONTROLLER_EXIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string CONTROLLER_PLACE_BUTTON {
            get {
                return ResourceManager.GetString("CONTROLLER_PLACE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click two points on the map to place tracks.
        /// </summary>
        internal static string CONTROLLER_RAIL_INITIAL_MESSAGE {
            get {
                return ResourceManager.GetString("CONTROLLER_RAIL_INITIAL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are obstacles in the way.
        /// </summary>
        internal static string CONTROLLER_RAIL_OBSTACLES {
            get {
                return ResourceManager.GetString("CONTROLLER_RAIL_OBSTACLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select starting point.
        /// </summary>
        internal static string CONTROLLER_RAIL_START_POINT {
            get {
                return ResourceManager.GetString("CONTROLLER_RAIL_START_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAILROAD.
        /// </summary>
        internal static string CONTROLLER_RAIL_TITLE {
            get {
                return ResourceManager.GetString("CONTROLLER_RAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string CONTROLLER_REMOVE_BUTTON {
            get {
                return ResourceManager.GetString("CONTROLLER_REMOVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour:.
        /// </summary>
        internal static string CONTROLLER_STATION_COLOUR {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_COLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station construction.
        /// </summary>
        internal static string CONTROLLER_STATION_CONSTRUCTION {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_CONSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string CONTROLLER_STATION_COST {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string CONTROLLER_STATION_DESIGN {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_DESIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        internal static string CONTROLLER_STATION_DIRECTION {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Length:.
        /// </summary>
        internal static string CONTROLLER_STATION_LENGTH {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string CONTROLLER_STATION_MAINTENANCE {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string CONTROLLER_STATION_MATERIALCONTROLLER_STATION_MATERIAL {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_MATERIALCONTROLLER_STATION_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CONTROLLER_STATION_NAME {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string CONTROLLER_STATION_PAGE {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string CONTROLLER_STATION_PLATFORM {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string CONTROLLER_STATION_SCALE {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string CONTROLLER_STATION_SIZE {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slim platform.
        /// </summary>
        internal static string CONTROLLER_STATION_SLIMPLATFORM {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_SLIMPLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATION.
        /// </summary>
        internal static string CONTROLLER_STATION_TITLE {
            get {
                return ResourceManager.GetString("CONTROLLER_STATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add new group.
        /// </summary>
        internal static string CONTROLLER_TRAIN_ADDNEWGROUP {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_ADDNEWGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This train has already been placed!.
        /// </summary>
        internal static string CONTROLLER_TRAIN_ALREADYPLACED {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_ALREADYPLACED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t place without tracks!.
        /// </summary>
        internal static string CONTROLLER_TRAIN_CANNOTPLACE_NOTRACKS {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_CANNOTPLACE_NOTRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sell this train?.
        /// </summary>
        internal static string CONTROLLER_TRAIN_CONFIRMSELL {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_CONFIRMSELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Diagram:.
        /// </summary>
        internal static string CONTROLLER_TRAIN_DIAGRAM {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Name:.
        /// </summary>
        internal static string CONTROLLER_TRAIN_NAME {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no cars!.
        /// </summary>
        internal static string CONTROLLER_TRAIN_NOCARS {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_NOCARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tracks.
        /// </summary>
        internal static string CONTROLLER_TRAIN_NORAIL {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_NORAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Train.
        /// </summary>
        internal static string CONTROLLER_TRAIN_PLACE {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sell....
        /// </summary>
        internal static string CONTROLLER_TRAIN_SELL {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy/Sell.
        /// </summary>
        internal static string CONTROLLER_TRAIN_TRADING {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_TRADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Type:.
        /// </summary>
        internal static string CONTROLLER_TRAIN_TYPE {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAIN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAIN PLACEMENT.
        /// </summary>
        internal static string CONTROLLER_TRAINPLACE_TITLE {
            get {
                return ResourceManager.GetString("CONTROLLER_TRAINPLACE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string FRIDAY {
            get {
                return ResourceManager.GetString("FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeTrain SDL.
        /// </summary>
        internal static string MAIN_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string MONDAY {
            get {
                return ResourceManager.GetString("MONDAY", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string SATURDAY {
            get {
                return ResourceManager.GetString("SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the TAO SDL Framework\nPlease download it from http://www.taoframework.com/\n\nThis application will now close..
        /// </summary>
        internal static string SDL_NOT_FOUND {
            get {
                return ResourceManager.GetString("SDL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string SUNDAY {
            get {
                return ResourceManager.GetString("SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string THURSDAY {
            get {
                return ResourceManager.GetString("THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string TUESDAY {
            get {
                return ResourceManager.GetString("TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string WEDNESDAY {
            get {
                return ResourceManager.GetString("WEDNESDAY", resourceCulture);
            }
        }
    }
}
